serenity.logging = VERBOSE
serenity.verbose.steps = true
serenity.console.colors = true
serenity.project.name = Resultados De Pruebas Funcionales
serenity.reports.show.step.details = true
serenity.report.format = single-page-html,json
serenity.outputDirectory = target/site/serenity
serenity.take.screenshots = FOR_EACH_ACTION
serenity.timeout = 10000
webdriver.wait.for.timeout = 16000
webdriver.timeouts.implicitlywait = 16000
webdriver.driver = chrome
chrome.switches = --disable-popup-blocking,--disable-download-notification,--test-type,--ignore-certificate-errors,--allow-running-insecure-content,--disable-translate,--always-authorize-plugins,--disable-extensions,--remote-allow-origins=*
serenity.rest.useSerenityRest = true
serenity.language = es
